services:
  - type: web
    name: shotota-v2
    runtime: node
    plan: standard
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_UPLOAD_DIR
        value: "/public/uploads"
      - key: DATABASE_URL
        fromDatabase:
          name: shotota-postgres
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: shotota-v2
          property: host
          prefix: "https://"
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: shotota-v2
          property: host
          prefix: "https://"
    preDeployCommand: npx prisma migrate deploy || npx prisma db push --accept-data-loss
    maxInstances: 3
    minInstances: 1

databases:
  - name: shotota-postgres
    engine: postgres
    version: "15"
    ipAllowList: []

